<?php

namespace Petlost\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PerdidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerdidoRepository extends EntityRepository
{
}
